language: python
python:
  - "3.6"
  - "nightly"

addons:
  postgresql: "9.6"

install:
    - pip install .

script: py.test -s


before_script:
  - psql -c "CREATE ROLE dbo LOGIN ENCRYPTED PASSWORD 'md568cefad35fed037c318b1e44cc3480cf';" -U postgres
  - psql -c "CREATE DATABASE test  WITH OWNER=dbo ENCODING='UTF8'" -U postgres
