language: python
python:
  - "3.6"

services:
  - postgresql

ddons:
  postgresql: "9.6"

install:
    - pip install .

script: py.test -sv

before_script:
  - psql -h localhost -U postgres -c "CREATE DATABASE test WITH ENCODING='UTF8'"
