language: python
python:
  - "3.6"
  - "nightly"

addons:
  postgresql: "9.5"

install:
    - pip install .

script: py.test -s


before_script:
  - psql -c "CREATE DATABASE test WITH ENCODING='UTF8'" -U postgres
