language: python
python:
  - "3.6"
  - "3.7"

services:
  - postgresql
addons:
  postgresql: "9.6"
  postgresql: "9.7"

install:
    - pip install .

script: py.test -s


before_script:
  - psql -c "CREATE DATABASE test  WITH ENCODING='UTF8'" -U postgres
