language: python
python:
  - "3.5"
  - "nightly"

addons:
  postgresql: "9.4"

install:
    - pip install .

script: py.test -s


before_script:
  - psql -c "CREATE ROLE dbo LOGIN ENCRYPTED PASSWORD 'md568cefad35fed037c318b1e44cc3480cf';" -U postgres
  - psql -c "CREATE DATABASE ci_test  WITH OWNER=dbo ENCODING='UTF8'" -U postgres
