version: 1
disable_existing_loggers: False

formatters:
    brief:
        format: '%(message)s'
    simple:
        '()': 'colorlog.ColoredFormatter'
        format: '[%(asctime)s] %(log_color)s[%(levelname)s] [%(name)s] %(white)s%(message)s'
        datefmt: '%H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout


root:
    level: DEBUG
    handlers: [console]

loggers:
    asyncio:
        level: INFO
    aiohttp:
        level: INFO
    watchdog:
        level: INFO
