version: 1
disable_existing_loggers: False

formatters:
    console: 
        format: '[%(asctime)s] %(message)s'
        datefmt: '%H:%M:%S'
    
    full:
        format: '%(levelname)s %(name)s %(asctime)s | %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        level: DEBUG
        # 'class': 'aiohttp_devtools.logs.DefaultHandler',
        class: 'logging.StreamHandler'
        formatter: console

    file:
        class : logging.handlers.TimedRotatingFileHandler
        formatter: full
        level: DEBUG
        filename: ../logs/alchemy-base.log
        when: H
        interval: 4
        backupCount: 100

loggers:
    test:
        level: DEBUG
        handlers: [console]
    redbean:
        level: DEBUG
        handlers: [console]
    aiohttp.web:
        level: DEBUG
        handlers: [console]
    adev:
        level: INFO
        handlers: [console]
        